### ISSUE TITLE
Shouldn't the training be awaited?

### ISSUE THREAD

**Issue by strblr** [zemlyansky/ppo-tfjs#1]
Hello,

Amazing work here, I have been looking for a tfjs PPO implementation since a long time and this is totally mind-blowing. Just tested it on a snake game and it works great. Very clean work.

Small question: Is there a specific reason for having made `train` async? Nothing is awaited inside and the method itself is not awaited:

https://github.com/zemlyansky/ppo-tfjs/blob/main/ppo.js#L548

**Comment by zemlyansky** [comment]
Thanks, @strblr! I don't remember why async is there:) Probably, you are right and it can be removed safely
